***
*** This file is part of the AmiGUS.audio driver.
***
*** AmiGUS.audio driver is free software: you can redistribute it and/or modify
*** it under the terms of the GNU Lesser General Public License as published by
*** the Free Software Foundation, version 3 of the License only.
***
*** AmiGUS.audio driver is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*** GNU LesserGeneral Public License for more details.
***
*** You should have received a copy of the GNU Lesser General Public License
*** along with AmiGUS.audio driver.  If not, see <http://www.gnu.org/licenses/>.
***

*** Audio Mode Definitions using m68k ASM to create data ***

    INCLUDE "devices/ahi.i"
    INCLUDE "libraries/ahi_sub.i"

TRUE                                EQU     1
FALSE                               EQU     0
AUDIO_ID_START                      EQU     $0ACF0000
* AmiGUS.audio extra tags
AHIDB_AmiGUS_PlayCopyFunction       EQU     AHIDB_UserBase+0
AHIDB_AmiGUS_PlayHwFormatId         EQU     AHIDB_UserBase+1
AHIDB_AmiGUS_RecCopyFunction        EQU     AHIDB_UserBase+2
AHIDB_AmiGUS_RecHwFormatId          EQU     AHIDB_UserBase+3

AMIGUS_PCM_S_PLAY_MONO_8BIT         EQU     0
AMIGUS_PCM_S_PLAY_STEREO_8BIT       EQU     1
AMIGUS_PCM_S_PLAY_MONO_16BIT        EQU     2
AMIGUS_PCM_S_PLAY_STEREO_16BIT      EQU     3
AMIGUS_PCM_S_PLAY_MONO_24BIT        EQU     4
AMIGUS_PCM_S_PLAY_STEREO_24BIT      EQU     5

AHI_AmiGUS_PlaybackCopy16to8        EQU     0
AHI_AmiGUS_PlaybackCopy16to16       EQU     1
AHI_AmiGUS_PlaybackCopy32to8        EQU     2
AHI_AmiGUS_PlaybackCopy32to16       EQU     3
AHI_AmiGUS_PlaybackCopy32to24       EQU     4

AMIGUS_PCM_S_REC_MONO_8BIT          EQU     6
AMIGUS_PCM_S_REC_STEREO_8BIT        EQU     0
AMIGUS_PCM_S_REC_MONO_16BIT         EQU     7
AMIGUS_PCM_S_REC_STEREO_16BIT       EQU     1

AHI_AmiGUS_RecordingCopy8Mto16S     EQU     0
AHI_AmiGUS_RecordingCopy8Sto16S     EQU     1
AHI_AmiGUS_RecordingCopy16Mto16S    EQU     2
AHI_AmiGUS_RecordingCopy16Sto16S    EQU     3

    MACRO LONGVAL
        dc.l \1
    ENDM

    MACRO TAGVAL
        LONGVAL \1
        LONGVAL \2
    ENDM

    MACRO TEXT0
        dc.b \1
        dc.b 0
    ENDM

    MACRO PAD
        CNOP 0,2
    ENDM

    MACRO STARTFORM
        LONGVAL ID_FORM
        LONGVAL FINALIZEFORM-BEGINFORM
BEGINFORM:
        LONGVAL ID_AHIM
    ENDM

    MACRO ENDFORM
FINALIZEFORM:
    ENDM

    MACRO STARTCHUNK
        LONGVAL \1
        LONGVAL FINALIZECHUNK$-BEGINCHUNK$
BEGINCHUNK$:
    ENDM

    MACRO ENDCHUNK
FINALIZECHUNK$:
    PAD
    ENDM

BEG:
    STARTFORM

    STARTCHUNK ID_AUDN
    TEXT0 "AmiGUS"
    ENDCHUNK

MODE0:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 0
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to8
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_8BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy8Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_8BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 8 bit mono - AHI Timing"
    ENDCHUNK

MODE1:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 1
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to8
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_8BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy8Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_8BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 8 bit stereo - AHI Timing"
    ENDCHUNK

MODE2:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 2
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to16
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_16BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit mono - AHI Timing"
    ENDCHUNK

MODE3:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 3
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to16
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_16BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit stereo - AHI Timing"
    ENDCHUNK

MODE4:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 4
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, TRUE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to8
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_8BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy8Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_8BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: Fast 8 bit mono - AHI Timing"
    ENDCHUNK

MODE5:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 5
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, TRUE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to8
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_8BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy8Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_8BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: Fast 8 bit stereo - AHI Timing"
    ENDCHUNK

MODE6:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 6
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, TRUE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to16
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_16BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit mono - AHI Timing"
    ENDCHUNK

MODE7:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 7
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, TRUE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy16to16
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_16BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: Fast 16 bit stereo - AHI Timing"
    ENDCHUNK

MODE8:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 8
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy32to8
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_8BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy8Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_8BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 8 bit mono - AHI Timing"
    ENDCHUNK

MODE9:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 9
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy32to8
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_8BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy8Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_8BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 8 bit stereo - AHI Timing"
    ENDCHUNK

MODE10:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 10
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy32to16
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_16BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 16 bit mono - AHI Timing"
    ENDCHUNK

MODE11:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 11
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, TRUE
    TAGVAL AHIDB_Record, TRUE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy32to16
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_16BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 16 bit stereo - AHI Timing"
    ENDCHUNK

MODE12:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 12
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 24
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, FALSE
    TAGVAL AHIDB_Record, FALSE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy32to24
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_MONO_24BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Mto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_MONO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 24 bit mono - AHI Timing"
    ENDCHUNK

MODE13:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 13
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 24
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_FullDuplex, FALSE
    TAGVAL AHIDB_Record, FALSE
    TAGVAL AHIDB_AmiGUS_PlayCopyFunction, AHI_AmiGUS_PlaybackCopy32to24
    TAGVAL AHIDB_AmiGUS_PlayHwFormatId, AMIGUS_PCM_S_PLAY_STEREO_24BIT
    TAGVAL AHIDB_AmiGUS_RecCopyFunction, AHI_AmiGUS_RecordingCopy16Sto16S
    TAGVAL AHIDB_AmiGUS_RecHwFormatId, AMIGUS_PCM_S_REC_STEREO_16BIT
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 24 bit stereo - AHI Timing"
    ENDCHUNK

* All LowCPU / LowLatency modes gone while we will be using AHI provided timing,
* aka AllocAudio -> (1) like everybody else.

    ENDFORM
