***
*** This file is part of the AmiGUS.audio driver.
***
*** AmiGUS.audio driver is free software: you can redistribute it and/or modify
*** it under the terms of the GNU Lesser General Public License as published by
*** the Free Software Foundation, version 3 of the License only.
***
*** AmiGUS.audio driver is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*** GNU LesserGeneral Public License for more details.
***
*** You should have received a copy of the GNU Lesser General Public License
*** along with AmiGUS.audio driver.  If not, see <http://www.gnu.org/licenses/>.
***

*** Audio Mode Definitions using m68k ASM to create data ***

    INCLUDE "devices/ahi.i"
    INCLUDE "libraries/ahi_sub.i"

TRUE            EQU     1
FALSE           EQU     0
AUDIO_ID_START  EQU     $0ACF0000

    MACRO LONGVAL
        dc.l \1
    ENDM

    MACRO TAGVAL
        LONGVAL \1
        LONGVAL \2
    ENDM

    MACRO TEXT0
        dc.b \1
        dc.b 0
    ENDM

    MACRO PAD
        CNOP 0,2
    ENDM

    MACRO STARTFORM
        LONGVAL ID_FORM
        LONGVAL FINALIZEFORM-BEGINFORM
BEGINFORM:
        LONGVAL ID_AHIM
    ENDM

    MACRO ENDFORM
FINALIZEFORM:
    ENDM

    MACRO STARTCHUNK
        LONGVAL \1
        LONGVAL FINALIZECHUNK$-BEGINCHUNK$
BEGINCHUNK$:
    ENDM

    MACRO ENDCHUNK
FINALIZECHUNK$:
    PAD
    ENDM

BEG:
    STARTFORM

    STARTCHUNK ID_AUDN
    TEXT0 "AmiGUS"
    ENDCHUNK

MODE0:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 0
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE    
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 8 bit mono - LowLatency"
    ENDCHUNK

MODE1:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 1
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 8 bit stereo - LowLatency"
    ENDCHUNK

MODE2:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 2
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit mono - LowLatency"
    ENDCHUNK

MODE3:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 3
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit stereo - LowLatency"
    ENDCHUNK

MODE4:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 4
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 16 bit mono - LowLatency"
    ENDCHUNK

MODE5:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 5
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 16 bit stereo - LowLatency"
    ENDCHUNK

MODE6:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 6
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 24
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 24 bit mono - LowLatency"
    ENDCHUNK

MODE7:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 7
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 24
    TAGVAL AHIDB_Realtime, TRUE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 24 bit stereo - LowLatency"
    ENDCHUNK

MODE10:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 10
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 8 bit mono - LowCPU"
    ENDCHUNK

MODE11:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 11
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 8
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 8 bit stereo - LowCPU"
    ENDCHUNK

MODE12:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 12
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit mono - LowCPU"
    ENDCHUNK

MODE13:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 13
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: 16 bit stereo - LowCPU"
    ENDCHUNK

MODE14:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 14
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, FALSE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 16 bit mono - LowCPU"
    ENDCHUNK

MODE15:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 15
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 16
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 16 bit stereo - LowCPU"
    ENDCHUNK

MODE16:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 16
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, FALSE
    TAGVAL AHIDB_Bits, 24
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 24 bit mono - LowCPU"
    ENDCHUNK

MODE17:
    STARTCHUNK ID_AUDM
BEGINTAG$:
    TAGVAL AHIDB_AudioID, AUDIO_ID_START + 17
    TAGVAL AHIDB_Volume, TRUE
    TAGVAL AHIDB_Panning, TRUE
    TAGVAL AHIDB_Stereo, TRUE
    TAGVAL AHIDB_Bits, 24
    TAGVAL AHIDB_Realtime, FALSE
    TAGVAL AHIDB_HiFi, TRUE
    TAGVAL AHIDB_MultTable, FALSE
    TAGVAL AHIDB_Name, MODENAME$-BEGINTAG$
    LONGVAL TAG_DONE
MODENAME$:
    TEXT0 "AmiGUS: HiFi 24 bit stereo - LowCPU"
    ENDCHUNK

    ENDFORM
